# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeTai' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'RealmSwift'
    pod 'Firebase/Core'
    pod 'SVProgressHUD'
    pod 'RealmSwift'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'Google/SignIn'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'

  # Pods for DeTai

  target 'DeTaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeTaiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
